[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/jegkarjavitas"
  to = "/pages/hdr.html"
  status = 200
  force = false

[[redirects]]
  from = "/horpadasjavitas"
  to = "/pages/pdr.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/pages/404.html"
  status = 200
  force = false